name: Checks
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: ./bin/scalafmt --test
  docs:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: sbt 'docs/mdoc'
  test-lts:
    name: Test (LTS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: sbt test
# For when we have newer Scala versions
#  test-newer:
#    name: Test (${{ matrix.scalaV }})
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        scalaV:
#          - "3.3.1"
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#      - run: sbt '++${{ matrix.scalaV }}! test'
