name: Building Website
on:
  push:
    tags: ["v*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - run: sbt 'docs/docusaurusPublishGhpages'
        env:
          GIT_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      - name: Check git diff
        if: ${{ failure() }}
        run: git diff
